version: '3.8'

services:
  # Caddy reverse proxy for HTTPS
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - chatterbox-network
    depends_on:
      - chatterbox-tts-server

  chatterbox-tts-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This build argument ensures only CPU dependencies are installed
        - RUNTIME=cpu
    # Remove external port exposure - only accessible via Caddy
    expose:
      - "8004"
    networks:
      - chatterbox-network
    volumes:
      # Mount local config file for persistence
      - ./config.yaml:/app/config.yaml
      # Mount local directories for persistent app data
      - ./voices:/app/voices
      - ./reference_audio:/app/reference_audio
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      # Named volume for Hugging Face model cache to persist across container rebuilds
      - hf_cache:/app/hf_cache
    networks:
      - chatterbox-network
    
    restart: unless-stopped
    environment:
      # Enable faster Hugging Face downloads inside the container
      - HF_HUB_ENABLE_HF_TRANSFER=1

# Define the named volumes
volumes:
  hf_cache:
  caddy_data:
  caddy_config:

# Define the network for service communication
networks:
  chatterbox-network:
    driver: bridge
